# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Set the working directory
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install Flask and requests
RUN pip install flask requests

# Make port 5001 available to the world outside this container
EXPOSE 5002

# Run app2.py when the container launches
CMD ["python3", "app2.py"]
