# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Set the working directory
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

#COPY requirements.txt requirements.txt
#RUN pip3 install -r requirements.txt

# Install Flask
RUN pip3 install flask 

# Make port 5000 available to the world outside this container
EXPOSE 5001

# Run app.py when the container launches
CMD ["python3", "app1.py"]