version: '3'

services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile.app1
    ports:
      - "5001:5001"
  app2:
    build:
      context: .
      dockerfile: Dockerfile.app2
    depends_on:
      - app1
    ports:
      - "5002:5002"
