apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: APP1_SERVICE_HOST
              value: "{{ .Values.app1Service.name }}"
            - name: APP1_SERVICE_PORT
              value: "{{ .Values.app1Service.port }}"
          ports:
            - containerPort: 5002
